"""
GitHub Integration — create issues and security advisories.
Build Rule 11: Integration failures don't crash the platform.
"""
import logging
import asyncio
from typing import Optional
import aiohttp

logger = logging.getLogger(__name__)


class GitHubIntegration:
    """
    Create GitHub Issues and Security Advisories for AgentRed findings.

    Configuration:
        token (str): GitHub Personal Access Token (requires repo scope)
        owner (str): Repository owner (username or organization)
        repo (str): Repository name
        labels (list): Default labels to add to issues
    """

    def __init__(self, token: str, owner: str, repo: str,
                 labels: Optional[list] = None, timeout: int = 10):
        """Initialize GitHub integration."""
        self.token = token
        self.owner = owner
        self.repo = repo
        self.labels = labels or ["agentred", "security"]
        self.timeout = timeout
        self._session: Optional[aiohttp.ClientSession] = None
        self.api_base = "https://api.github.com"

    async def __aenter__(self):
        """Async context manager entry."""
        self._session = aiohttp.ClientSession()
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        """Async context manager exit."""
        if self._session:
            await self._session.close()

    def _get_session(self) -> aiohttp.ClientSession:
        """Get or create session."""
        if not self._session:
            self._session = aiohttp.ClientSession()
        return self._session

    def _get_headers(self) -> dict:
        """Get GitHub API headers."""
        return {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28"
        }

    def _build_issue_body(self, finding: dict) -> str:
        """Build GitHub issue body from finding."""
        body = f"""
## Finding Details

- **Severity:** {finding.get('severity', 'unknown')}
- **Confidence:** {finding.get('confidence', 0.0)}%
- **Category:** {finding.get('category', 'unknown')}
- **Finding ID:** {finding.get('id')}

## Description

{finding.get('description', 'No description provided')}

## Evidence

{finding.get('evidence', 'No evidence provided')}

## Remediation

{finding.get('remediation', 'No remediation provided')}

## Tags

{', '.join([f'`{tag}`' for tag in finding.get('tags', [])])}

---

_Generated by AgentRed Red Teaming Platform_
"""
        return body.strip()

    async def create_issue(self, finding: dict) -> Optional[str]:
        """
        Create a GitHub issue for a finding.

        Args:
            finding (dict): Finding data with keys: id, name, description, severity, evidence, etc.

        Returns:
            Optional[str]: GitHub issue URL or None if failed
        """
        try:
            session = self._get_session()

            issue_data = {
                "title": f"[{finding.get('severity', 'unknown').upper()}] {finding.get('name', 'AgentRed Finding')}",
                "body": self._build_issue_body(finding),
                "labels": self.labels + finding.get("tags", []),
            }

            url = f"{self.api_base}/repos/{self.owner}/{self.repo}/issues"
            headers = self._get_headers()

            async with session.post(
                url,
                json=issue_data,
                headers=headers,
                timeout=aiohttp.ClientTimeout(total=self.timeout)
            ) as resp:
                if resp.status == 201:
                    data = await resp.json()
                    issue_url = data.get("html_url")
                    issue_num = data.get("number")
                    logger.info(f"Created GitHub issue #{issue_num} for finding {finding.get('id')}")
                    return issue_url
                else:
                    error_text = await resp.text()
                    logger.error(f"GitHub error {resp.status}: {error_text}")
                    return None

        except asyncio.TimeoutError:
            logger.error(f"GitHub timeout after {self.timeout}s")
            return None
        except Exception as e:
            logger.error(f"GitHub create_issue error: {e}")
            return None

    async def create_security_advisory(self, finding: dict) -> Optional[str]:
        """
        Create a GitHub Security Advisory for a critical finding.

        Args:
            finding (dict): Finding data

        Returns:
            Optional[str]: Advisory URL or None if failed
        """
        try:
            session = self._get_session()

            advisory_data = {
                "summary": finding.get('name', 'AgentRed Finding'),
                "description": finding.get('description', 'No description'),
                "severity": self._map_severity_to_advisory_level(finding.get('severity')),
                "cvss_vector_string": finding.get('cvss_vector'),
                "cwe_ids": [finding.get('cwe_id')] if finding.get('cwe_id') else [],
                "cve_id": finding.get('cve'),
                "vulnerable_functions": [finding.get('vulnerable_function')] if finding.get('vulnerable_function') else [],
            }

            # Remove None values
            advisory_data = {k: v for k, v in advisory_data.items() if v is not None}

            url = f"{self.api_base}/repos/{self.owner}/{self.repo}/security-advisories"
            headers = self._get_headers()

            async with session.post(
                url,
                json=advisory_data,
                headers=headers,
                timeout=aiohttp.ClientTimeout(total=self.timeout)
            ) as resp:
                if resp.status in (201, 200):
                    data = await resp.json()
                    advisory_url = data.get("html_url") or data.get("url")
                    logger.info(f"Created GitHub security advisory for finding {finding.get('id')}")
                    return advisory_url
                else:
                    error_text = await resp.text()
                    logger.warning(f"GitHub advisory creation {resp.status}: {error_text}")
                    return None

        except asyncio.TimeoutError:
            logger.error(f"GitHub timeout after {self.timeout}s")
            return None
        except Exception as e:
            logger.error(f"GitHub create_security_advisory error: {e}")
            return None

    def _map_severity_to_advisory_level(self, severity: str) -> str:
        """Map AgentRed severity to GitHub advisory severity."""
        severity_map = {
            "critical": "critical",
            "high": "high",
            "medium": "moderate",
            "low": "low",
            "info": "low",
        }
        return severity_map.get(severity, "moderate")

    async def test_connection(self) -> bool:
        """
        Test connectivity to GitHub API.

        Returns:
            bool: True if connection successful, False otherwise
        """
        try:
            session = self._get_session()
            url = f"{self.api_base}/user"
            headers = self._get_headers()

            async with session.get(
                url,
                headers=headers,
                timeout=aiohttp.ClientTimeout(total=5)
            ) as resp:
                if resp.status == 200:
                    logger.info("GitHub connection test successful")
                    return True
                else:
                    logger.error(f"GitHub test failed: {resp.status}")
                    return False

        except Exception as e:
            logger.error(f"GitHub connection test failed: {e}")
            return False

    async def close(self):
        """Close the session."""
        if self._session:
            await self._session.close()
