"""
GitLab Integration — create issues for findings.
Build Rule 11: Integration failures don't crash the platform.
"""
import logging
import asyncio
from typing import Optional
import aiohttp

logger = logging.getLogger(__name__)


class GitLabIntegration:
    """
    Create GitLab issues for AgentRed findings.

    Configuration:
        instance_url (str): GitLab instance URL (e.g. https://gitlab.com)
        private_token (str): GitLab private access token
        project_id (int or str): GitLab project ID or path
        labels (list): Default labels to add to issues
    """

    def __init__(self, instance_url: str, private_token: str,
                 project_id: Optional[str] = None,
                 labels: Optional[list] = None, timeout: int = 10):
        """Initialize GitLab integration."""
        self.instance_url = instance_url.rstrip("/")
        self.private_token = private_token
        self.project_id = project_id
        self.labels = labels or ["agentred", "security"]
        self.timeout = timeout
        self._session: Optional[aiohttp.ClientSession] = None

    async def __aenter__(self):
        """Async context manager entry."""
        self._session = aiohttp.ClientSession()
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        """Async context manager exit."""
        if self._session:
            await self._session.close()

    def _get_session(self) -> aiohttp.ClientSession:
        """Get or create session."""
        if not self._session:
            self._session = aiohttp.ClientSession()
        return self._session

    def _get_headers(self) -> dict:
        """Get GitLab API headers."""
        return {
            "PRIVATE-TOKEN": self.private_token,
            "Content-Type": "application/json"
        }

    def _build_description(self, finding: dict) -> str:
        """Build GitLab issue description from finding."""
        description = f"""
## Finding Details

- **Severity:** {finding.get('severity', 'unknown')}
- **Confidence:** {finding.get('confidence', 0.0)}%
- **Category:** {finding.get('category', 'unknown')}
- **Finding ID:** {finding.get('id')}

## Description

{finding.get('description', 'No description provided')}

## Evidence

{finding.get('evidence', 'No evidence provided')}

## Remediation

{finding.get('remediation', 'No remediation provided')}

## Tags

{', '.join([f'`{tag}`' for tag in finding.get('tags', [])])}

---

_Generated by AgentRed Red Teaming Platform_
"""
        return description.strip()

    async def create_issue(self, finding: dict) -> Optional[str]:
        """
        Create a GitLab issue for a finding.

        Args:
            finding (dict): Finding data with keys: id, name, description, severity, evidence, etc.

        Returns:
            Optional[str]: GitLab issue URL or None if failed
        """
        if not self.project_id:
            logger.error("GitLab project_id not configured")
            return None

        try:
            session = self._get_session()

            issue_data = {
                "title": f"[{finding.get('severity', 'unknown').upper()}] {finding.get('name', 'AgentRed Finding')}",
                "description": self._build_description(finding),
                "labels": ",".join(self.labels + finding.get("tags", [])),
            }

            # Add priority based on severity
            severity_to_priority = {
                "critical": 1,  # Urgent
                "high": 2,      # High
                "medium": 3,    # Medium
                "low": 4,       # Low
                "info": 5,      # Very Low
            }
            priority = severity_to_priority.get(finding.get('severity'), 3)

            url = f"{self.instance_url}/api/v4/projects/{self.project_id}/issues"
            headers = self._get_headers()

            async with session.post(
                url,
                json=issue_data,
                headers=headers,
                timeout=aiohttp.ClientTimeout(total=self.timeout)
            ) as resp:
                if resp.status in (200, 201):
                    data = await resp.json()
                    issue_url = data.get("web_url")
                    issue_id = data.get("id")
                    logger.info(f"Created GitLab issue #{issue_id} for finding {finding.get('id')}")
                    return issue_url
                else:
                    error_text = await resp.text()
                    logger.error(f"GitLab error {resp.status}: {error_text}")
                    return None

        except asyncio.TimeoutError:
            logger.error(f"GitLab timeout after {self.timeout}s")
            return None
        except Exception as e:
            logger.error(f"GitLab create_issue error: {e}")
            return None

    async def update_issue(self, issue_iid: int, update_data: dict) -> bool:
        """
        Update a GitLab issue.

        Args:
            issue_iid (int): GitLab issue IID (internal ID)
            update_data (dict): Fields to update

        Returns:
            bool: True if successful, False otherwise
        """
        if not self.project_id:
            logger.error("GitLab project_id not configured")
            return False

        try:
            session = self._get_session()

            url = f"{self.instance_url}/api/v4/projects/{self.project_id}/issues/{issue_iid}"
            headers = self._get_headers()

            async with session.put(
                url,
                json=update_data,
                headers=headers,
                timeout=aiohttp.ClientTimeout(total=self.timeout)
            ) as resp:
                if resp.status in (200, 204):
                    logger.info(f"Updated GitLab issue #{issue_iid}")
                    return True
                else:
                    error_text = await resp.text()
                    logger.error(f"GitLab update error {resp.status}: {error_text}")
                    return False

        except asyncio.TimeoutError:
            logger.error(f"GitLab timeout after {self.timeout}s")
            return False
        except Exception as e:
            logger.error(f"GitLab update_issue error: {e}")
            return False

    async def test_connection(self) -> bool:
        """
        Test connectivity to GitLab instance.

        Returns:
            bool: True if connection successful, False otherwise
        """
        try:
            session = self._get_session()
            url = f"{self.instance_url}/api/v4/user"
            headers = self._get_headers()

            async with session.get(
                url,
                headers=headers,
                timeout=aiohttp.ClientTimeout(total=5)
            ) as resp:
                if resp.status == 200:
                    logger.info("GitLab connection test successful")
                    return True
                else:
                    logger.error(f"GitLab test failed: {resp.status}")
                    return False

        except Exception as e:
            logger.error(f"GitLab connection test failed: {e}")
            return False

    async def close(self):
        """Close the session."""
        if self._session:
            await self._session.close()
