"""
Jira Integration — create tickets for critical findings.
Build Rule 11: Integration failures don't crash the platform.
"""
import logging
import asyncio
from typing import Optional
import aiohttp

logger = logging.getLogger(__name__)

# Severity to Jira priority mapping
SEVERITY_TO_PRIORITY = {
    "critical": "Highest",
    "high": "High",
    "medium": "Medium",
    "low": "Low",
    "info": "Lowest",
}


class JiraIntegration:
    """
    Create and manage Jira tickets for AgentRed findings.

    Configuration:
        instance_url (str): Jira instance URL (e.g. https://company.atlassian.net)
        api_token (str): Jira API token (not password)
        username (str): Jira username/email
        project_key (str): Jira project key (e.g. "SEC")
        issue_type (str): Issue type for findings (default: "Bug")
        auto_assign_component (bool): Auto-assign component based on finding category
    """

    def __init__(self, instance_url: str, api_token: str, username: str,
                 project_key: str, issue_type: str = "Bug",
                 auto_assign_component: bool = True,
                 timeout: int = 10):
        """Initialize Jira integration."""
        self.instance_url = instance_url.rstrip("/")
        self.api_token = api_token
        self.username = username
        self.project_key = project_key
        self.issue_type = issue_type
        self.auto_assign_component = auto_assign_component
        self.timeout = timeout
        self._session: Optional[aiohttp.ClientSession] = None

    async def __aenter__(self):
        """Async context manager entry."""
        self._session = aiohttp.ClientSession()
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        """Async context manager exit."""
        if self._session:
            await self._session.close()

    def _get_session(self) -> aiohttp.ClientSession:
        """Get or create session."""
        if not self._session:
            self._session = aiohttp.ClientSession()
        return self._session

    def _get_auth_header(self) -> dict:
        """Get Basic auth header."""
        import base64
        credentials = base64.b64encode(
            f"{self.username}:{self.api_token}".encode()
        ).decode()
        return {"Authorization": f"Basic {credentials}"}

    def _severity_to_priority(self, severity: str) -> str:
        """Map AgentRed severity to Jira priority."""
        return SEVERITY_TO_PRIORITY.get(severity, "Medium")

    def _build_description(self, finding: dict) -> str:
        """Build Jira issue description from finding."""
        description = f"""
h2. Finding Details

*ID:* {finding.get('id')}
*Severity:* {finding.get('severity', 'unknown')}
*Category:* {finding.get('category', 'unknown')}
*Confidence:* {finding.get('confidence', 0.0)}%

h3. Description
{finding.get('description', 'No description provided')}

h3. Evidence
{finding.get('evidence', 'No evidence provided')}

h3. Remediation
{finding.get('remediation', 'No remediation provided')}

h3. Tags
{', '.join(finding.get('tags', []))}

_Generated by AgentRed Red Teaming Platform_
"""
        return description.strip()

    async def create_issue(self, finding: dict) -> Optional[str]:
        """
        Create a Jira issue for a finding.

        Args:
            finding (dict): Finding data with keys: id, name, description, severity, evidence, etc.

        Returns:
            Optional[str]: Jira issue key (e.g. "SEC-123") or None if failed
        """
        try:
            session = self._get_session()

            issue_data = {
                "fields": {
                    "project": {"key": self.project_key},
                    "issuetype": {"name": self.issue_type},
                    "summary": f"[{finding.get('severity', 'unknown').upper()}] {finding.get('name', 'AgentRed Finding')}",
                    "description": self._build_description(finding),
                    "priority": {"name": self._severity_to_priority(finding.get('severity'))},
                    "labels": finding.get("tags", []) + ["agentred"],
                }
            }

            # Auto-assign component
            if self.auto_assign_component and finding.get("category"):
                issue_data["fields"]["components"] = [
                    {"name": finding.get("category")}
                ]

            url = f"{self.instance_url}/rest/api/3/issue"
            headers = {
                **self._get_auth_header(),
                "Content-Type": "application/json"
            }

            async with session.post(
                url,
                json=issue_data,
                headers=headers,
                timeout=aiohttp.ClientTimeout(total=self.timeout)
            ) as resp:
                if resp.status == 201:
                    data = await resp.json()
                    issue_key = data.get("key")
                    logger.info(f"Created Jira issue {issue_key} for finding {finding.get('id')}")
                    return issue_key
                else:
                    error_text = await resp.text()
                    logger.error(f"Jira error {resp.status}: {error_text}")
                    return None

        except asyncio.TimeoutError:
            logger.error(f"Jira timeout after {self.timeout}s")
            return None
        except Exception as e:
            logger.error(f"Jira create_issue error: {e}")
            return None

    async def update_issue(self, issue_key: str, update_data: dict) -> bool:
        """
        Update a Jira issue.

        Args:
            issue_key (str): Jira issue key (e.g. "SEC-123")
            update_data (dict): Fields to update

        Returns:
            bool: True if successful, False otherwise
        """
        try:
            session = self._get_session()

            url = f"{self.instance_url}/rest/api/3/issue/{issue_key}"
            headers = {
                **self._get_auth_header(),
                "Content-Type": "application/json"
            }

            request_body = {"fields": update_data}

            async with session.put(
                url,
                json=request_body,
                headers=headers,
                timeout=aiohttp.ClientTimeout(total=self.timeout)
            ) as resp:
                if resp.status in (204, 200):
                    logger.info(f"Updated Jira issue {issue_key}")
                    return True
                else:
                    error_text = await resp.text()
                    logger.error(f"Jira update error {resp.status}: {error_text}")
                    return False

        except asyncio.TimeoutError:
            logger.error(f"Jira timeout after {self.timeout}s")
            return False
        except Exception as e:
            logger.error(f"Jira update_issue error: {e}")
            return False

    async def test_connection(self) -> bool:
        """
        Test connectivity to Jira instance.

        Returns:
            bool: True if connection successful, False otherwise
        """
        try:
            session = self._get_session()
            url = f"{self.instance_url}/rest/api/3/myself"
            headers = self._get_auth_header()

            async with session.get(
                url,
                headers=headers,
                timeout=aiohttp.ClientTimeout(total=5)
            ) as resp:
                if resp.status == 200:
                    logger.info("Jira connection test successful")
                    return True
                else:
                    logger.error(f"Jira test failed: {resp.status}")
                    return False

        except Exception as e:
            logger.error(f"Jira connection test failed: {e}")
            return False

    async def close(self):
        """Close the session."""
        if self._session:
            await self._session.close()
